plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
  - _pages
  - _posts
  - _data
  - _includes
  - _layouts

remote_theme: pages-themes/cayman@v0.2.0

title: ix-cli
description: > # this means to ignore newlines until "baseurl:"
  ix-cli is a command line tool for interacting with the ix.io pastebin service.

baseurl: /ix
show_downloads: true

github:
  is_project_page: false
  pypi_url: https://pypi.org/project/ix-cli/
  tar_url: https://pypi.org/project/ix-cli/#files
  zip_url: https://pypi.org/project/ix-cli/#files