site_name: ix-cli
site_url: https://arnos-stuff.github.io
repo_url: https://github.com/arnos-stuff/ix
repo_name: ix

plugins:
  - social
  - tags:
      tags_file: tags.md

site_dir: site/ix


extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arno_shae
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/arnos-stuff/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/arnoveldock
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/724287271364198520

markdown_extensions:
  - markdown.extensions.abbr
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - tables

nav:
    - Home: index.md
    - Commands: cli.md
    - Contributing: future-work.md
    - Tags: tags.md
    - About: about.md
theme:
  name: material
  font:
    text: Fira Sans
    code: Fira Code
  logo: assets/Wide-Logo-SM.svg
  favicon: assets/blob48.png
  features:
    - navigation.footer

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/palette-swatch-outline
        name: Default Theme
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/format-color-fill
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

dev_addr: "127.0.0.1:8000"